# Generated by Django 4.2.6 on 2023-10-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='MessageModel',
        ),
    ]
